version: "3.9"

services:
  template_nodejs:
    platform: linux/arm64
    image: template_nodejs
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules

    env_file:
      - .env
    ports:
      - 3332:3332
    expose:
      - 3332
    depends_on:
      template_nodejs_postgres:
        condition: service_started

    networks:
      template_nodejs_devnet:
        ipv4_address: 172.18.1.2

  template_nodejs_postgres:
    image: postgres:10.3
    container_name: template_nodejs_postgres
    restart: "no"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ=America/Fortaleza
      - PGTZ=America/Fortaleza
    volumes:
      - template_nodejs_postgres:/var/lib/postgresql/data
    ports:
      - 5430:5432
    expose:
      - 5430
    networks:
      template_nodejs_devnet:
        ipv4_address: 172.18.1.3

volumes:
  template_nodejs_postgres:


networks:
  template_nodejs_devnet:
    name: template_nodejs_devnet
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/16
          gateway: 172.18.1.1
